import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/head/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
      {/* This was making the 3d model render twice */}
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
